#!/bin/sh
if command -v limine-mkinitcpio >/dev/null 2>&1; then
	limine-mkinitcpio
elif command -v mkinitcpio >/dev/null 2>&1; then
	mkinitcpio --allpresets
elif command -v limine-dracut >/dev/null 2>&1; then
	limine-dracut
elif command -v dracut >/dev/null 2>&1; then
	dracut --regenerate-all --force
elif command -v /usr/lib/booster/regenerate_images >/dev/null 2>&1; then
	/usr/lib/booster/regenerate_images
else
	echo 'Could not find a supported initramfs generator. Please regenerate your initramfs manually.'
	exit 127
fi
