#!/bin/sh
if command -v limine-mkinitcpio >/dev/null 2>&1; then
    limine-mkinitcpio
elif command -v mkinitcpio >/dev/null 2>&1; then
    mkinitcpio --allpresets
elif command -v limine-dracut >/dev/null 2>&1; then
    limine-dracut
elif command -v dracut >/dev/null 2>&1; then
    dracut --regenerate-all --force
elif [ -x /usr/lib/booster/regenerate_images ]; then
    /usr/lib/booster/regenerate_images
else
    echo 'Could not find a supported initramfs generator. Please regenerate your initramfs manually.' >&2
    exit 1
fi
